name: Check Format

on: [push, pull_request]

jobs:
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mvn com.coveo:fmt-maven-plugin:check