name: AWS CodeBuild CI
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *" # Daily at 00:00 UTC (4 PM PDT)

permissions:
  id-token: write
  contents: read

jobs:
  runCodeBuildCI:
    name: Run CodeBuild CI
    environment: ci
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 3600
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start CodeBuild Batch Build
        run: |
          echo "BATCH_ID<<EOF" >> $GITHUB_ENV
          ./.github/scripts/start_codebuild_batch.sh ${{ github.sha }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash
      - name: Wait for CodeBuild completion
        run: ./.github/scripts/poll_build_status.sh ${{ env.BATCH_ID }}
        shell: bash